# esptool.py --port COM3 flash_id
# esptool.py --port COM3 --baud 115200 write_flash -fm dio -fs 32m 0x00000 tasmota.bin

esphome:
  name: pzem
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret Wifi_SSID
  password: !secret Wifi_PWD
  # Optional manual IP
  manual_ip:
    static_ip: 192.168.1.11
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1
    dns2: 8.8.8.8
 # This will cause ESPHome to only enable the access point when no connection to the WiFi router can be made.
  ap:
    ssid: pzemRecovery

# Enable captive portal
captive_portal:

web_server:
   port: 80

# Enable logging
logger:
  baud_rate: 1
  level: VERY_VERBOSE



# Enable ota
ota:

# Enable Home Assistant API
api:

time:
  - platform: homeassistant
    id: homeassistant_time


binary_sensor:
  - platform: status
    name: " Stato sensore"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: Address_IP
    ssid:
      name: SSID
    bssid:
      name: BSSID
  - platform: version
    name: "ESPHome Version"

modbus:
  uart_id: uartpzem

uart:
  - id: uartpzem
    rx_pin: GPIO05
    tx_pin: GPIO04
    baud_rate: 9600
    stop_bits: 2

sensor:
  - platform: pzemac
    address: 1
    current:
      name: "PZEM-004T V3 Current(1)"
    voltage:
      name: "PZEM-004T V3 Voltage(1)"
    energy:
      name: "PZEM-004T V3 Energy(1)"
    power:
      name: "PZEM-004T V3 Power(1)"
    frequency:
      name: "PZEM-004T V3 Frequency(1)"
    power_factor:
      name: "PZEM-004T V3 Power Factor(1)"
    update_interval: 60s

  - platform: pzemac
    address: 2
    current:
      name: "PZEM-004T V3 Current (2)"
    voltage:
      name: "PZEM-004T V3 Voltage(2)"
    energy:
      name: "PZEM-004T V3 Energy(2)"
    power:
      name: "PZEM-004T V3 Power(2)"
    frequency:
      name: "PZEM-004T V3 Frequency(2)"
    power_factor:
      name: "PZEM-004T V3 Power Factor(2)"
    update_interval: 60s

  - platform: uptime
    name: Uptime
    icon: mdi:clock-outline
    update_interval: 300s
    unit_of_measurement: days
    filters:
      - multiply: 0.000011574
  - platform: wifi_signal
    name: "Segnale wifi sensore"
    update_interval: 60s
